defaults:
  - _self_
  - override hydra/launcher: submitit_local


# ------- Desired Motion parameters -----------------------------------
# specify the gait, bound or jump or trot or combined
gaits: ["trot"]  # trot, jump, bound

# desired velocity
vx_des_min: 0.0 # m_s
vx_des_max: 0.3  # m/s
vy_des_min: 0.0 # m_s
vy_des_max: 0.0  # m/s
w_des_min: 0.0  # rad/s
w_des_max: 0.0   # rad/s

# Pertubation variables
mu_base_pos: 
  trot: 0.0
  jump: 0.0
  bound: 0.0
sigma_base_pos: # base position
  trot: 0.1 
  jump: 0.0
  bound: 0.05
mu_joint_pos: 
  trot: 0.0
  jump: 0.0
  bound: 0.0
sigma_joint_pos: # joint position
  trot: 0.2
  jump: 0.1
  bound: 0.1
mu_base_ori:
  trot: 0.0
  jump: 0.0
  bound: 0.0
sigma_base_ori: # base orientation
  trot: 0.7
  jump: 0.2
  bound: 0.2
mu_vel:
  trot: 0.0
  jump: 0.0
  bound: 0.0
sigma_vel: # joint velocity
  trot: 0.2
  jump: 0.2
  bound: 0.2


# ------- Model Parameters -----------------------------------
action_type: "pd_target" #"pd_target", "torque", "structured"
normalize_policy_input: True

# ------- Saving Paths ----------------------------------
save_data: True
data_save_path: "./data" # folder to store database snapshots
suffix: '' # suffix model name for saving

#------------------ Simulation Rollout Parameters ----------------------------
sim_dt: 0.001

#------------------ Data related Parameters ----------------------------
n_state: 43
n_action: 12
goal_horizon: 1
kp: 2.
kd: .1

#---------- Iterative Algorithm Variables --------------------------
# warmup
num_rollouts_warmup: 10
num_pertubations_per_replanning_warmup: 1
episode_length_warmup: 1500

# Evaluation
num_rollouts_eval: 10
num_pertubations_per_replanning_eval: 1
episode_length_eval: 5000

# main locosafedagger loop
num_iterations_locosafedagger: 3 # as a start

num_rollouts_per_iteration_data: 20
num_replannings_on_nom_traj_data: 1
num_pertubations_per_replanning_data: 2

episode_length_data: 10000
num_steps_to_block_under_safety: 2000 # 4 gait cycle
ending_mpc_rollout_episode_length: 1000

#---------- Data buffer variables --------------------------
database_size: 10000000

#---------- Network parameters-------------
num_hidden_layer: 3
hidden_dim: 512
batch_norm: True
goal_type: 'vc'  # cc: contact constraint, vc: veloctiy constraint

#---------- Training parameters-------------
batch_size: 256
learning_rate: 0.002
n_train_frac: 0.9 # fraction of the data used for training
n_epoch_warmup: 15
n_epoch_data: 15


hydra:
  job:
    chdir: False
  run:
    dir: ${data_save_path}/hydra_logs/${now:%Y_%m_%d}_${now:%H_%M_%S}
  sweep:
    dir: ${data_save_path}/${now:%Y_%m_%d}_${now:%H_%M_%S}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_$${gaits}/.slurm
