defaults:
  - _self_
  - override hydra/launcher: submitit_local


# ------- Desired Motion parameters -----------------------------------
# specify the gait, bound or jump or trot or combined
gaits: ["trot"]  # trot, jump, bound

vx_des_min: 0.2 # m_s
vx_des_max: 0.2  # m/s
vy_des_min: 0.0 # m_s
vy_des_max: 0.0  # m/s
w_des_min: 0.0  # rad/s
w_des_max: 0.0   # rad/s


# ------- Model Parameters -----------------------------------
action_type: "pd_target" #"pd_target", "torque", "structured"
normalize_policy_input: True

# ------- Saving Paths ----------------------------------
save_data: True
data_save_path: "./data" # folder to store database snapshots
suffix: '' # suffix model name for saving

#------------------ Simulation Rollout Parameters ----------------------------
episode_length: 3000  # steps in rollout
sim_dt: 0.001

# Pertubation variables
mu_base_pos: 0.0
sigma_base_pos: 0.1 # base position
mu_joint_pos: 0.0
sigma_joint_pos: 0.2 # joint position
mu_base_ori: 0.0
sigma_base_ori: 0.7 # base orientation
mu_vel: 0.0
sigma_vel: 0.2 # joint velocity

#------------------ Data related Parameters ----------------------------
n_state: 43
n_action: 12
goal_horizon: 1
kp: 2.
kd: .1

#---------- Data buffer variables --------------------------
database_size: 1000000

#---------- Network parameters-------------
num_hidden_layer: 3
hidden_dim: 512
batch_norm: True
goal_type: 'vc'  # cc: contact constraint, vc: veloctiy constraint

#---------- Training parameters-------------
batch_size: 256
learning_rate: 0.002
n_epoch: 150
n_train_frac: 0.9 # fraction of the data used for training


hydra:
  job:
    chdir: False
  run:
    dir: ${data_save_path}/hydra_logs/${now:%Y_%m_%d}_${now:%H_%M_%S}
  sweep:
    dir: ${data_save_path}/${now:%Y_%m_%d}_${now:%H_%M_%S}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_$${gaits}/.slurm
