program: sweep_policy.py
command:
  - ${env}
  - python3
  - ${program}
method: grid
metric:
  name: num_successful_rollouts
  goal: maximize
parameters: 
  learning_rate: 
    values: [0.001, 0.0015, 0.002, 0.0025, 0.003]
  batch_size:
    values: [256, 512]
  epochs:
    values: [150, 200]
  num_hidden_layer: 
    values: [3, 4]
  hidden_dim: 
    values: [256, 512]